// _LogWindow_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sunday, 13 November 2005 7:23:04 PM Pacific/Auckland

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _LogWindow_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ArrayController _arrayController0, _arrayController1, _arrayController2;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn11, _eoTableColumn12, _eoTableColumn13, _eoTableColumn14, _eoTableColumn15, _eoTableColumn16, _eoTableColumn17, _eoTableColumn18, _eoTableColumn19, _eoTableColumn2, _eoTableColumn20, _eoTableColumn21, _eoTableColumn22, _eoTableColumn23, _eoTableColumn24, _eoTableColumn25, _eoTableColumn26, _eoTableColumn27, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOView _nsSplitView0;
    com.webobjects.foundation.NSTimestampFormatter _nsTimestampFormatter0, _nsTimestampFormatter1, _nsTimestampFormatter2, _nsTimestampFormatter3, _nsTimestampFormatter4, _nsTimestampFormatter5;
    javax.swing.JPanel _nsView0;

    public _LogWindow_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTimestampFormatter5 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _nsTimestampFormatter4 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _nsTimestampFormatter3 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _nsTimestampFormatter2 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _nsTimestampFormatter1 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _nsTimestampFormatter0 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%b %d, %Y"), "");
        _arrayController2 = (ArrayController)_registered(new ArrayController(), "MoveLogController");
        _eoTableColumn27 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn26 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn25 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn24 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn23 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn22 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn21 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn20 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _arrayController1 = (ArrayController)_registered(new ArrayController(), "ReceiveLogController");
        _eoTableColumn19 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn18 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn17 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn16 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn15 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn14 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn13 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn12 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn11 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _arrayController0 = (ArrayController)_registered(new ArrayController(), "SendLogController");
        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsSplitView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }
    }

    protected void _init() {
        super._init();
        _nsTableView2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController2, "nothing", _nsTableView2), ""));
        _eoTableColumn27.setMinWidth(36);
        _eoTableColumn27.setMaxWidth(1000);
        _eoTableColumn27.setPreferredWidth(60);
        _eoTableColumn27.setWidth(60);
        _eoTableColumn27.setResizable(true);
        _eoTableColumn27.setHeaderValue("Status");
        if ((_eoTableColumn27.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn27.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn26.setMinWidth(31);
        _eoTableColumn26.setMaxWidth(1000);
        _eoTableColumn26.setPreferredWidth(61);
        _eoTableColumn26.setWidth(61);
        _eoTableColumn26.setResizable(true);
        _eoTableColumn26.setHeaderValue("Total");
        if ((_eoTableColumn26.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn26.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn25.setMinWidth(10);
        _eoTableColumn25.setMaxWidth(1000);
        _eoTableColumn25.setPreferredWidth(52);
        _eoTableColumn25.setWidth(52);
        _eoTableColumn25.setResizable(true);
        _eoTableColumn25.setHeaderValue("Error");
        if ((_eoTableColumn25.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn25.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn24.setMinWidth(46);
        _eoTableColumn24.setMaxWidth(1000);
        _eoTableColumn24.setPreferredWidth(56);
        _eoTableColumn24.setWidth(56);
        _eoTableColumn24.setResizable(true);
        _eoTableColumn24.setHeaderValue("Pending");
        if ((_eoTableColumn24.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn24.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn23.setMinWidth(10);
        _eoTableColumn23.setMaxWidth(1000);
        _eoTableColumn23.setPreferredWidth(53);
        _eoTableColumn23.setWidth(53);
        _eoTableColumn23.setResizable(true);
        _eoTableColumn23.setHeaderValue("Sent");
        if ((_eoTableColumn23.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn23.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn22.setMinWidth(10);
        _eoTableColumn22.setMaxWidth(1000);
        _eoTableColumn22.setPreferredWidth(105);
        _eoTableColumn22.setWidth(105);
        _eoTableColumn22.setResizable(true);
        _eoTableColumn22.setHeaderValue("End");
        if ((_eoTableColumn22.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn22.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn21.setMinWidth(10);
        _eoTableColumn21.setMaxWidth(1000);
        _eoTableColumn21.setPreferredWidth(105);
        _eoTableColumn21.setWidth(105);
        _eoTableColumn21.setResizable(true);
        _eoTableColumn21.setHeaderValue("Start");
        if ((_eoTableColumn21.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn21.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn20.setMinWidth(40);
        _eoTableColumn20.setMaxWidth(1000);
        _eoTableColumn20.setPreferredWidth(78);
        _eoTableColumn20.setWidth(78);
        _eoTableColumn20.setResizable(true);
        _eoTableColumn20.setHeaderValue("Direction");
        if ((_eoTableColumn20.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn20.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView2.table().addColumn(_eoTableColumn20);
        _nsTableView2.table().addColumn(_eoTableColumn21);
        _nsTableView2.table().addColumn(_eoTableColumn22);
        _nsTableView2.table().addColumn(_eoTableColumn23);
        _nsTableView2.table().addColumn(_eoTableColumn24);
        _nsTableView2.table().addColumn(_eoTableColumn25);
        _nsTableView2.table().addColumn(_eoTableColumn26);
        _nsTableView2.table().addColumn(_eoTableColumn27);
        _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView2.table().setRowHeight(20);
        _nsTableView1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController1, "nothing", _nsTableView1), ""));
        _eoTableColumn19.setMinWidth(36);
        _eoTableColumn19.setMaxWidth(1000);
        _eoTableColumn19.setPreferredWidth(59);
        _eoTableColumn19.setWidth(59);
        _eoTableColumn19.setResizable(true);
        _eoTableColumn19.setHeaderValue("Status");
        if ((_eoTableColumn19.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn19.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn18.setMinWidth(31);
        _eoTableColumn18.setMaxWidth(1000);
        _eoTableColumn18.setPreferredWidth(46);
        _eoTableColumn18.setWidth(46);
        _eoTableColumn18.setResizable(true);
        _eoTableColumn18.setHeaderValue("Total");
        if ((_eoTableColumn18.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn18.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn17.setMinWidth(10);
        _eoTableColumn17.setMaxWidth(1000);
        _eoTableColumn17.setPreferredWidth(48);
        _eoTableColumn17.setWidth(48);
        _eoTableColumn17.setResizable(true);
        _eoTableColumn17.setHeaderValue("Error");
        if ((_eoTableColumn17.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn17.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn16.setMinWidth(10);
        _eoTableColumn16.setMaxWidth(1000);
        _eoTableColumn16.setPreferredWidth(50);
        _eoTableColumn16.setWidth(50);
        _eoTableColumn16.setResizable(true);
        _eoTableColumn16.setHeaderValue("Sent");
        if ((_eoTableColumn16.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn16.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn15.setMinWidth(10);
        _eoTableColumn15.setMaxWidth(1000);
        _eoTableColumn15.setPreferredWidth(50);
        _eoTableColumn15.setWidth(50);
        _eoTableColumn15.setResizable(true);
        _eoTableColumn15.setHeaderValue("End");
        if ((_eoTableColumn15.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn15.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn14.setMinWidth(10);
        _eoTableColumn14.setMaxWidth(1000);
        _eoTableColumn14.setPreferredWidth(49);
        _eoTableColumn14.setWidth(49);
        _eoTableColumn14.setResizable(true);
        _eoTableColumn14.setHeaderValue("Start");
        if ((_eoTableColumn14.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn14.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn13.setMinWidth(10);
        _eoTableColumn13.setMaxWidth(1000);
        _eoTableColumn13.setPreferredWidth(67);
        _eoTableColumn13.setWidth(67);
        _eoTableColumn13.setResizable(true);
        _eoTableColumn13.setHeaderValue("To/From");
        if ((_eoTableColumn13.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn13.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn12.setMinWidth(10);
        _eoTableColumn12.setMaxWidth(1000);
        _eoTableColumn12.setPreferredWidth(51);
        _eoTableColumn12.setWidth(51);
        _eoTableColumn12.setResizable(true);
        _eoTableColumn12.setHeaderValue("Study");
        if ((_eoTableColumn12.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn12.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn11.setMinWidth(40);
        _eoTableColumn11.setMaxWidth(1000);
        _eoTableColumn11.setPreferredWidth(73);
        _eoTableColumn11.setWidth(73);
        _eoTableColumn11.setResizable(true);
        _eoTableColumn11.setHeaderValue("Patient");
        if ((_eoTableColumn11.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn11.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn10.setMinWidth(40);
        _eoTableColumn10.setMaxWidth(1000);
        _eoTableColumn10.setPreferredWidth(71);
        _eoTableColumn10.setWidth(71);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("Direction");
        if ((_eoTableColumn10.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn10.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView1.table().addColumn(_eoTableColumn10);
        _nsTableView1.table().addColumn(_eoTableColumn11);
        _nsTableView1.table().addColumn(_eoTableColumn12);
        _nsTableView1.table().addColumn(_eoTableColumn13);
        _nsTableView1.table().addColumn(_eoTableColumn14);
        _nsTableView1.table().addColumn(_eoTableColumn15);
        _nsTableView1.table().addColumn(_eoTableColumn16);
        _nsTableView1.table().addColumn(_eoTableColumn17);
        _nsTableView1.table().addColumn(_eoTableColumn18);
        _nsTableView1.table().addColumn(_eoTableColumn19);
        _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView1.table().setRowHeight(20);
        _nsTableView0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "nothing", _nsTableView0), ""));
        _eoTableColumn9.setMinWidth(36);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(53);
        _eoTableColumn9.setWidth(53);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("Status");
        if ((_eoTableColumn9.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn9.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn8.setMinWidth(31);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(49);
        _eoTableColumn8.setWidth(49);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Total");
        if ((_eoTableColumn8.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn8.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn7.setMinWidth(10);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(48);
        _eoTableColumn7.setWidth(48);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Error");
        if ((_eoTableColumn7.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn7.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn6.setMinWidth(10);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(50);
        _eoTableColumn6.setWidth(50);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Sent");
        if ((_eoTableColumn6.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn6.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn5.setMinWidth(10);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(50);
        _eoTableColumn5.setWidth(50);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("End");
        if ((_eoTableColumn5.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn5.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn4.setMinWidth(10);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(49);
        _eoTableColumn4.setWidth(49);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("Start");
        if ((_eoTableColumn4.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn4.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(67);
        _eoTableColumn3.setWidth(67);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("To/From");
        if ((_eoTableColumn3.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn3.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn2.setMinWidth(10);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(47);
        _eoTableColumn2.setWidth(47);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Study");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn1.setMinWidth(40);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(77);
        _eoTableColumn1.setWidth(77);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Patient");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(74);
        _eoTableColumn0.setWidth(74);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Direction");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView0.table().addColumn(_eoTableColumn0);
        _nsTableView0.table().addColumn(_eoTableColumn1);
        _nsTableView0.table().addColumn(_eoTableColumn2);
        _nsTableView0.table().addColumn(_eoTableColumn3);
        _nsTableView0.table().addColumn(_eoTableColumn4);
        _nsTableView0.table().addColumn(_eoTableColumn5);
        _nsTableView0.table().addColumn(_eoTableColumn6);
        _nsTableView0.table().addColumn(_eoTableColumn7);
        _nsTableView0.table().addColumn(_eoTableColumn8);
        _nsTableView0.table().addColumn(_eoTableColumn9);
        _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView0.table().setRowHeight(20);
        if (!(_nsSplitView0.getLayout() instanceof EOViewLayout)) { _nsSplitView0.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(612, 293);
        _nsTableView0.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsTableView0);
        _nsTableView1.setSize(612, 94);
        _nsTableView1.setLocation(0, 302);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsTableView1);
        _nsTableView2.setSize(612, 129);
        _nsTableView2.setLocation(0, 405);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsTableView2);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsSplitView0.setSize(612, 534);
        _nsSplitView0.setLocation(13, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSplitView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsSplitView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(638, 562);
            _eoFrame0.setTitle("Network Logs");
            _eoFrame0.setLocation(30, 588);
            _eoFrame0.setSize(638, 562);
        }
    }
}
