# 

DSTDIR=		../..
MANDIR=		$(DSTDIR)/man
INCDIR=		$(DSTDIR)/include
BINDIR=		$(DSTDIR)/test
LIBDIR=		$(DSTDIR)/$(ARCH)/lib
SRCLIBPPDIR=	$(DSTDIR)/$(ARCH)/lib
LINTLIBDIR=	$(LIBDIR)/lint

CPPFLAGS=	-I$(INCDIR) -I.. -DXTFUNCPROTO -g 
CFLAGS=		-g
LINTFLAGS=	-hbac

SOURCES= \
		TestRead.c


OBJECTS=	$(SOURCES:%.c=$(VARIANT)%.o)
PROG=		$(SOURCES:%.c=%)

LIBRARY=	$(LIBDIR)/libP.a


VAR=		$(TARGET_ARCH:-%=%)
VARIANT=	$(VAR)/

.KEEP_STATE:
.INIT:	$(VAR)

all:		$(PROG)

$(PROG): $$(OBJECTS) 
		$(LINK.cc) -Bstatic -g -o $(VARIANT)$@ $(VARIANT)$@.o \
		$(LIBDIR)/libP.a $(LIBDIR)/libJpglossy.a \
		$(LIBDIR)/libJpglless.a $(LIBDIR)/libDicomDir.a -lm

$(LIBRARY): FORCE
		cd $(SRCLIBPDIR); make

FORCE:

$(VAR):
		test -d $@ || mkdir $@

$$(VARIANT)%.o: %.c
		$(COMPILE.cc) $< -o $@

