#!/bin/bash

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSI3DPreferencePane/$1.lproj
cp -R OSI3DPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSI3DPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIAutoroutingPreferencePane/$1.lproj
cp -R OSIAutoroutingPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIAutoroutingPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSICDPreferencePane/$1.lproj
cp -R OSICDPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSICDPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSICustomImageAnnotations/$1.lproj
cp -R OSICustomImageAnnotations.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSICustomImageAnnotations

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIDatabasePreferencePane/$1.lproj
cp -R OSIDatabasePreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIDatabasePreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIGeneralPreferencePane/$1.lproj
cp -R OSIGeneralPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIGeneralPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIHangingPreferencePane/$1.lproj
cp -R OSIHangingPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIHangingPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIHotKeys/$1.lproj
cp -R OSIHotKeys.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIHotKeys

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIListenerPreferencePane/$1.lproj
cp -R OSIListenerPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIListenerPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSILocationsPreferencePane/$1.lproj
cp -R OSILocationsPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSILocationsPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIPETPreferencePane/$1.lproj
cp -R OSIPETPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIPETPreferencePane

rm -R -f /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIViewerPreferencePane/$1.lproj
cp -R OSIViewerPreferencePane.prefPane/Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.7.1/Preference\ Panes/OSIViewerPreferencePane

