#!/bin/bash

mv OSI3DPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSI3DPreferencePane


mv OSIAutoroutingPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIAutoroutingPreferencePane


mv OSICDPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSICDPreferencePane


mv OSICustomImageAnnotations./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSICustomImageAnnotations


mv OSIDatabasePreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIDatabasePreferencePane


mv OSIGeneralPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIGeneralPreferencePane


mv OSIHangingPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIHangingPreferencePane


mv OSIHotKeys./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIHotKeysPreferencePane


mv OSIListenerPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIListenerPreferencePane


mv OSILocationsPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSILocationsPreferencePane


mv OSIPETPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIPETPreferencePane


mv OSIViewerPreferencePane./Contents/Resources/$1.lproj /Users/antoinerosset/Desktop/Localized3.6.1/Preference\ Panes/OSIViewerPreferencePane

