/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <AppKit/NSView.h>
#import <Foundation/NSGeometry.h>

@class NSButton, NSCell, NSString;

@interface NSFrameView : NSView
{
    unsigned int styleMask;
    NSString *_title;
    NSCell *titleCell;
    NSButton *closeButton;
    NSButton *zoomButton;
    NSButton *minimizeButton;
    BOOL resizeByIncrement;
    BOOL unused;
    unsigned char tabViewCount;
    NSSize resizeParameter;
    int shadowState;
}

+ (void)initialize;
+ (void)initTitleCell:(id)fp8 styleMask:(unsigned int)fp12;
+ (NSRect)frameRectForContentRect:(NSRect)fp8 styleMask:(unsigned int)fp24;
+ (NSRect)contentRectForFrameRect:(NSRect)fp8 styleMask:(unsigned int)fp24;
+ (struct _NSSize)minFrameSizeForMinContentSize:(struct _NSSize)fp8 styleMask:(unsigned int)fp16;
+ (struct _NSSize)minContentSizeForMinFrameSize:(struct _NSSize)fp8 styleMask:(unsigned int)fp16;
+ (float)minFrameWidthWithTitle:(id)fp8 styleMask:(unsigned int)fp12;
+ (unsigned int)_validateStyleMask:(unsigned int)fp8;
- (id)initWithFrame:(NSRect)fp8 styleMask:(unsigned int)fp24 owner:(id)fp28;
- (id)initWithFrame:(NSRect)fp8;
- (void)dealloc;
- (void)finalize;
- (void)shapeWindow;
- (void)tileAndSetWindowShape:(BOOL)fp8;
- (void)tile;
- (void)drawRect:(NSRect)fp8;
- (void)_drawFrameRects:(NSRect)fp8;
- (void)drawFrame:(NSRect)fp8;
- (void)drawThemeContentFill:(NSRect)fp8 inView:(id)fp24;
- (void)drawWindowBackgroundRect:(NSRect)fp8;
- (void)drawWindowBackgroundRegion:(void *)fp8;
- (float)contentAlpha;
- (void)_windowChangedKeyState;
- (void)_updateButtonState;
- (BOOL)_isSheet;
- (BOOL)_isUtility;
- (void)setShadowState:(int)fp8;
- (int)shadowState;
- (BOOL)_canHaveToolbar;
- (BOOL)_toolbarIsInTransition;
- (BOOL)_toolbarIsShown;
- (BOOL)_toolbarIsHidden;
- (void)_showToolbarWithAnimation:(BOOL)fp8;
- (void)_hideToolbarWithAnimation:(BOOL)fp8;
- (float)_distanceFromToolbarBaseToTitlebar;
- (int)_shadowType;
- (unsigned int)_shadowFlags;
- (void)_setShadowParameters;
- (void)_drawFrameShadowAndFlushContext:(id)fp8;
- (void)setUpGState;
- (void)adjustHalftonePhase;
- (void)systemColorsDidChange:(id)fp8;
- (id)frameColor;
- (id)contentFill;
- (void)tabViewAdded;
- (void)tabViewRemoved;
- (id)title;
- (void)setTitle:(id)fp8;
- (id)titleCell;
- (void)initTitleCell:(id)fp8;
- (void)setResizeIncrements:(struct _NSSize)fp8;
- (struct _NSSize)resizeIncrements;
- (void)setAspectRatio:(struct _NSSize)fp8;
- (struct _NSSize)aspectRatio;
- (unsigned int)styleMask;
- (id)representedFilename;
- (void)setRepresentedFilename:(id)fp8;
- (void)setDocumentEdited:(BOOL)fp8;
- (void)_setFrameNeedsDisplay:(BOOL)fp8;
- (BOOL)frameNeedsDisplay;
- (id)titleFont;
- (NSRect)_maxTitlebarTitleRect;
- (NSRect)titlebarRect;
- (void)_setUtilityWindow:(BOOL)fp8;
- (void)_setNonactivatingPanel:(BOOL)fp8;
- (void)setIsClosable:(BOOL)fp8;
- (void)setIsResizable:(BOOL)fp8;
- (id)closeButton;
- (id)minimizeButton;
- (id)zoomButton;
- (struct _NSSize)miniaturizedSize;
- (void)_clearDragMargins;
- (void)_resetDragMargins;
- (void)setTitle:(id)fp8 andDefeatWrap:(BOOL)fp12;
- (NSRect)frameRectForContentRect:(NSRect)fp8 styleMask:(unsigned int)fp24;
- (NSRect)contentRectForFrameRect:(NSRect)fp8 styleMask:(unsigned int)fp24;
- (struct _NSSize)minFrameSizeForMinContentSize:(struct _NSSize)fp8 styleMask:(unsigned int)fp16;
- (NSRect)dragRectForFrameRect:(NSRect)fp8;
- (NSRect)contentRect;
- (struct _NSSize)minFrameSize;

@end

