// _Send_EOArchive_English.java
// Generated by EnterpriseObjects palette at Monday, January 9, 2006 12:04:53 PM America/Denver

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _Send_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4;
    javax.swing.JButton _nsButton0, _nsButton1;
    javax.swing.JComboBox _nsComboBox0, _popup0, _popup1;
    javax.swing.JPanel _nsView0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2, _jRadioButton3, _jRadioButton4;

    public _Send_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField241");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField24");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField22");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton1");
        _jRadioButton4 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Only Secondary Captures (SC)"), "");
        _jRadioButton3 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Only key images"), "");
        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("All images"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "keyImageMatrix")) != null)) {
            _nsMatrix1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix1");
        } else {
            _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 4, 2), "NSMatrix11");
        }

        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("OsiriX STORE-SCU, transfer syntax:"), "NSButtonCell1");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Dicom Offis STORE-SCU, transfer syntax:"), "NSButtonCell");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "DICOMSendTool")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(2, 1, 4, 2), "NSMatrix1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "syntaxListOsiriX")) != null)) {
            _popup1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup1");
        } else {
            _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "syntaxListOffis")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "serverList")) != null)) {
            _nsComboBox0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsComboBox0");
        } else {
            _nsComboBox0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSComboBox");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "numberImagesTextField")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Send"), "NSButton");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "SelectServer");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "endSelectServer", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _connect(_owner(), _nsMatrix1, "keyImageMatrix");
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "DICOMSendTool");
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _popup1.setModel(new javax.swing.DefaultComboBoxModel());
            _popup1.addItem("Explicit Little Endian");
            _popup1.addItem("JPEG 2000 Lossless");
            _popup1.addItem("JPEG 2000 Lossy 10:1");
            _popup1.addItem("JPEG 2000 Lossy 20:1");
            _popup1.addItem("JPEG 2000 Lossy 50:1");
            _popup1.addItem("JPEG Lossless");
            _popup1.addItem("JPEG High Quality (9)");
            _popup1.addItem("JPEG Medium High Quality (8)");
            _popup1.addItem("JPEG Medium Quality (7)");
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _connect(_owner(), _popup1, "syntaxListOsiriX");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Implicit little endian only (-xi)");
            _popup0.addItem("All uncompressed TS, explicit, little endian first (-xe)");
            _popup0.addItem("All uncompressed TS, explicit, big endian first (-xb)");
            _popup0.addItem("JPEG lossless (-xs)");
            _popup0.addItem("RLE lossless (-xr)");
            _popup0.addItem("JPEG 2000 Lossless (-xv)");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "syntaxListOffis");
        }

        if (_replacedObjects.objectForKey("_nsComboBox0") == null) {
            _connect(_nsComboBox0, _owner(), "dataSource");
        }

        _nsComboBox0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectServer", _nsComboBox0), ""));

        if (_replacedObjects.objectForKey("_nsComboBox0") == null) {
            
        }

        if (_replacedObjects.objectForKey("_nsComboBox0") == null) {
            _connect(_owner(), _nsComboBox0, "serverList");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "numberImagesTextField");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "endSelectServer", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Send:");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Select which tool to use:");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Select destination (DICOM Server):");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Number of selected files to send:");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jRadioButton4, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton3, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton2, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix1") == null) {
            _jRadioButton2.setSize(249, 18);
            _jRadioButton2.setLocation(0, 0);
            _nsMatrix1.add(_jRadioButton2);
            _jRadioButton3.setSize(249, 18);
            _jRadioButton3.setLocation(0, 20);
            _nsMatrix1.add(_jRadioButton3);
            _jRadioButton4.setSize(249, 18);
            _jRadioButton4.setLocation(0, 40);
            _nsMatrix1.add(_jRadioButton4);
            _setFontForComponent(_nsMatrix1, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton0.setSize(281, 25);
            _jRadioButton0.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton1.setSize(281, 25);
            _jRadioButton1.setLocation(0, 27);
            _nsMatrix0.add(_jRadioButton1);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup1") == null) {
            _setFontForComponent(_popup1, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(false);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(71, 26);
        _nsButton0.setLocation(580, 197);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsButton1.setSize(75, 26);
        _nsButton1.setLocation(500, 197);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsTextField1.setSize(230, 17);
        _nsTextField1.setLocation(11, 4);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField0.setSize(345, 17);
        _nsTextField0.setLocation(306, 4);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField2.setSize(230, 17);
        _nsTextField2.setLocation(11, 29);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _nsComboBox0.setSize(342, 26);
        _nsComboBox0.setLocation(309, 27);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsComboBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsComboBox0);
        _nsMatrix0.setSize(281, 52);
        _nsMatrix0.setLocation(23, 81);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsTextField3.setSize(271, 17);
        _nsTextField3.setLocation(11, 57);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField3);
        _nsMatrix1.setSize(249, 58);
        _nsMatrix1.setLocation(23, 163);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsMatrix1);
        _nsTextField4.setSize(271, 17);
        _nsTextField4.setLocation(11, 139);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField4);
        _popup0.setSize(338, 26);
        _popup0.setLocation(310, 81);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _popup1.setSize(338, 26);
        _popup1.setLocation(310, 108);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView0.add(_popup1);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(660, 233);
            _eoFrame0.setTitle("DICOM Send");
            _eoFrame0.setLocation(581, 228);
            _eoFrame0.setSize(660, 233);
        }
    }
}
